services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    volumes:
      - uptime:/app/data
    restart: always
    
volumes:
    uptime:
        size: 4Gi
